# Generated by Django 5.1.3 on 2024-11-25 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
