# Generated by Django 5.1.3 on 2024-11-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_loan_due_date_loan_is_returned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
    ]
