# Generated by Django 5.1.3 on 2024-11-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_loan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
