# Generated by Django 5.1.3 on 2024-11-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
