# Generated by Django 5.1.3 on 2024-11-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_appeal_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
